--- #YAML:1.0
name:               XML-xmlapi
version:            0.01
abstract:           The xmlapi was an expat wrapper library I wrote in 2000 in ANSI C; this is its Perl port.
author:
    - Michael Roberts <michael@vivtek.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
